[package]
name = "netnet"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
async-compat = "0.2.5"
crossbeam-queue = "0.3.13"
log = "0.4.33"
quinn = "0.11.11"
rcgen = "0.14.8"
rustls = { version = "0.23.42", default-features = false, features = ["tls12", "ring", "std"] }
thiserror = "2.0.18"

[dev-dependencies]
pretty_env_logger = "0.5.0"
rand = "0.10.2"
